stages:
 - docker-build

docker-build:
  image: docker.io/library/docker:latest
  stage: docker-build
  script:
    # - export C7N_COMMIT_SHA=$(echo ${CI_COMMIT_SHA:-abcdefghijklmhopqrst} | awk '{print substr($1,1,8)}')
    - docker login ${MY_DOCKER_REGISTRY} --password ${DOCKER_PASSWORD} --username ${DOCKER_USER}
    # - docker build . -t ${MY_DOCKER_REGISTRY}/hzero-fe-public/distributed-nginx:${C7N_COMMIT_SHA}
    - docker build . -t ${MY_DOCKER_REGISTRY}/hzero-fe-public/distributed-nginx:0.0.1
    # - docker push ${MY_DOCKER_REGISTRY}/hzero-fe-public/distributed-nginx:${C7N_COMMIT_SHA}
    # - docker tag ${MY_DOCKER_REGISTRY}/hzero-fe-public/distributed-nginx:${C7N_COMMIT_SHA} ${MY_DOCKER_REGISTRY}/hzero-fe-public/distributed-nginx:0.0.1
    - docker push ${MY_DOCKER_REGISTRY}/hzero-fe-public/distributed-nginx:1.24.0
    # - docker push ${MY_DOCKER_REGISTRY}/hzero-fe-public/distributed-nginx:0.0.1
  only:
    - master
#   tags:
#     - docker
